version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      assignees:
        - 'or-yam'
      open-pull-requests-limit: 10
      target-branch: 'main'
